### ISSUE TITLE
Publish basicmodem on pypi

### ISSUE THREAD

**Issue by andrey-git** [vroomfonde1/basicmodem#1]
Could you publish this package on Pypi, so it can be fetched without specifying the github URL?

home-assistant/home-assistant#7069

**Comment by vroomfonde1** [comment]
Hi,

Sure!  I will take care of publishing basicmodem to pypi in next week or so.

regards,
Tim (vroomfonde1)

**Comment by vroomfonde1** [comment]
Hi, published to pypi.

https://pypi.python.org/pypi/basicmodem/0.7

Let me know if you find any issues or want me to update homeassistant modem_callerid sensor and requirements_all.txt as well.
regards,
Tim
